<?php
return [

    'retype' => 'Retype',

    'delete_question' => 'Voulez-vous vraiment supprimer cet élément: %s ?',

    'click_here_to_pick_up_date' => 'Cliquez ici pour récupérer la date',

    'user_name' => "Nom d'utilisateur",

    'password' => "Mot de passe",

    'sign_in' => 'Connexion',

    'Verification' => 'Veuillez entrer le code de vérification',

    'login_failed' => 'La connexion a échoué !',

    'tools' => 'Outils'

];