<?php

// DIRECTION CONSTANTS ======================

const DIR = "ltr";

const IS_RTL = false;

const TEXT_START = "left";

const TEXT_END = "right";

const TEXT_START_UC = "Left";

const TEXT_END_UC = "Right";

// ===============================================

const EDIT = "Modifier";

const DELETE = "Supprimé";

const SAVE = "Enregistré";

const SEND = "Envoyer";

const VIEW = "Vue";

const YES = "Oui";

const NO = "Non";


