<?php
use Semiorbit\Data\Msg;

return [

    Msg::DBERR => "Désolé ! Une erreur inattendue s'est produite. Veuillez réessayer plus tard !",

    Msg::DBOK => "Enregistré avec succès!",

    Msg::FILL_ALL => "Veuillez remplir tous les champs !",

    Msg::FILL_ALL_REQUIRED => "Veuillez remplir tous les champs obligatoires (*)!",

    Msg::DATA_EXISTS => "Les données existent !",

    Msg::INVALID_TEL => "Veuillez saisir un numéro de <em>téléphone</em> valide! Seuls les chiffres sont autorisés.",

    Msg::INVALID_VALUE => "Veuillez saisir une <em>valeur</em> valide!",

    Msg::INVALID_URL => "Veuillez saisir un numéro de <em>mobile</em> valide! Seuls les chiffres sont autorisés.",

    Msg::INVALID_EMAIL => "Veuillez entrer un <em>e-mail</em> valide!",

    Msg::RETYPE_PASSWORD => "Veuillez retaper le <em>mot de passe</em>!",

    Msg::ROW_DELETED => "Supprimé avec succès!",

    Msg::REGISTER_OK => "Bienvenue ! Enregistré avec succès.",

    Msg::REGISTER_CANCEL => "Inscription annulée!",

    Msg::REGISTER_ACTIVE => "Votre inscription a été réactivée. Merci!",

    Msg::REGISTER_FAILED => "Désolé, vous n'êtes pas enregistré!",

    Msg::UPLOAD_OK => "Téléchargé avec succès",

    Msg::UPLOAD_FAILED => "Échec du téléchargement!",

    Msg::FILE_TYPE_ERR => "Type de fichier invalide!",

    Msg::RESIZE_FAILED => "Impossible de redimensionner la photo téléchargée!",

    Msg::FILE_SIZE_ERR => "Taille de fichier invalide!",

    Msg::NOT_VERIFIED => "Désolé! Veuillez saisir le code de vérification correct ci-dessous.",

    Msg::COMMENTED => "Merci ! Votre message a été envoyé avec succès."

];