<?php

// DIRECTION CONSTANTS ======================

const DIR = "rtl";

const IS_RTL = true;

const TEXT_START = "right";

const TEXT_END = "left";

const TEXT_START_UC = "Right";

const TEXT_END_UC = "Left";

// ===============================================

const EDIT = "تحرير";

const DELETE = "حذف";

const SAVE =  "حفظ";

const SEND = "إرسال";

const VIEW = "عرض";

const YES = "نعم";

const NO = "لا";