<?php
define("pub_date","تاريخ النشر");
define("Back","عودة");
define("Back_to_home","عودة إلى الرئيسية");
define("user_name","اسم المستخدم");
define("password","كلمة المرور");
define("Re-Type","أعد كتابة ");
define("sign_in","دخول");
define("sign_out","تسجيل خروج");
define("log_in","تسجيل دخول");
define("Edit","تحرير");
define("AddNew","إدراج جديد");
define("Delete","حذف");
define("delete_question", "هل تريد بالتأكيد حذف العنصر المسمى: %s ؟");
define("Save", "حفظ");
define("Send","إرسال");
define("Login_Failed","بيانات الدخول غير صحيحة!");
define("more","المزيد");
define("Hidden","إخفاء (لا يمكن للزوار معاينة هذا السجل)");
define("LastUpdate","آخر تحديث");
define("CreationDate", "تاريخ الإدراج");
define("NDate","آخر تحديث");
define("Visits","الزيارات");
define("lang","اللغة");
define("Related_Pages","صفحات ذات صلة");
define("Visitors","Visits");
define("View","عرض");

define("Home","البداية");
define("Articles","المقالات");
define("Read_More","إقرأ المزيد");
define("Remove_Pic","حذف الصورة");

define("enter_key_word","أدخل كلمة البحث");
define("Tools","لوحة التحكم");
define("Cancel_Map_Point","إلغاء النقطة");
define("ALL", "الكل");
define("Yes","نعم");
define("No","لا");
define("Start_Typing_Keywords", "حدد البند المناسب...");
define("ClickHereToPickUpTheDate", "انقر هنا لتحديد التاريخ");
define("Male", "ذكر");
define("Female", "أنثى");


define("Hide","إخفاء");
define("Show","إظهار");

define("yes","نعم");
define("no","لا");
define("read_more","إقرأ المزيد");
define("Verification","يرجى إدخال الأحرف الظاهرة في المكان المخصص");
define("This_helps_us_to_prevent_automatic_registration","الرجاء إدخال المحارف الظاهرة أدناه في الصورة (غير حساس لحالة الأحرف)");
define("Please_enter_the_string_shown_in_the_image_above","");
define("Search","بحث");
define("Required", "مطلوب");
define("Root", "--الجذر--");
define("Public", "عام");
define("Private", "خاص");

//PAGINATION >>>>>>>>>>>>>>>
define("DIR", "rtl");
define("TextStart","right");
define("TextEnd","left");

//END PAGINATION <<<<<<<<<<<

define("Change_Admin_Password", "تغير كلمة مرور المدير");

/*
define("second","ثانية");
define("minute","دقيقة");
define("hour","ساعة");
define("day","يوم");
define("week","أسبوع");
define("month","شهر");
define("year","سنة");
define("decade","عقد");

define("seconds","ثانية");
define("minutes","دقيقة");
define("hours","ساعة");
define("days","أيام");
define("weeks","أسابيع");
define("months","أشهر");
define("years","سنة");
define("decades","عقود");

define("since","منذ");
define("ago","مضت");
define("m_ago","مضى");
*/