<?php
return [

    'retype' => 'أعد كتابة ',

    'delete_question' => 'هل تريد بالتأكيد حذف العنصر المسمى: %s ؟',

    'click_here_to_pick_up_date' => 'انقر هنا لتحديد التاريخ',

    'user_name' => "اسم المستخدم",

    'password' => "كلمة المرور",

    'sign_in' => 'دخول',

    'Verification' => 'يرجى إدخال الأحرف الظاهرة في المكان المخصص',

    'login_failed' => 'بيانات الدخول غير صحيحة!',

    'tools' => 'لوحة التحكم'

];