<?php
use Semiorbit\Data\Msg;

return [
   
    Msg::DBERR             =>   "نأسف لحصول خطأ أثناء الكتابة إلى قاعدة البيانات! يرجى إعادة المحاولة لاحقاً...",

    Msg::DBOK              =>   "تم حفظ البيانات بنجاح!",

    Msg::FILL_ALL          =>   "يجب إدخال جميع الحقول!",

    Msg::FILL_ALL_REQUIRED =>   "يجب إدخال جميع الحقول المطلوبة (*) !",

    Msg::DATA_EXISTS       =>   "البيانات موجودة.. يرجى إدخال بيانات جديدة!",

    Msg::INVALID_TEL       =>   "الرجاء إدخال رقم <em>هاتف</em> صحيح! فقط الأرقام مسموحة..",

    Msg::INVALID_VALUE     =>   "الرجاء إدخال <em>قيمة</em> صحيحة!",

    Msg::INVALID_URL       =>   "الرجاء إدخال رقم <em>موبايل</em> صحيح! فقط الأرقام مسموحة.",

    Msg::INVALID_EMAIL     =>   "الرجاء إدخال <em>بريد إلكتروني</em> صحيح!",

    Msg::RETYPE_PASSWORD   =>   "الرجاء إعادة إدخال  <em>كلمة المرور</em>!",
    
    Msg::ROW_DELETED       =>   "تم الحذف بنجاح!",

    Msg::REGISTER_OK       =>   "شكراً لك! تم تسجيلك بنجاح...",

    Msg::REGISTER_CANCEL   =>   "تم إلغاء إشتراكك بنجاح! شكراً لك.",

    Msg::REGISTER_ACTIVE   =>   "شكراً لك! تم إعادة تفعيل إشتراكك بنجاح..",

    Msg::REGISTER_FAILED   =>   "المعذرة! أنت غير مسجل لدينا سابقاً.",

    Msg::UPLOAD_OK         =>   "تم رفع الملف بنجاح!",

    Msg::UPLOAD_FAILED     =>   "خطأ أثناء رفع الملف!",

    Msg::FILE_TYPE_ERR     =>   "نوع الملف غير صالح!",

    Msg::RESIZE_FAILED     =>   "فشل في تغيير حجم الصورة!",
    
    Msg::FILE_SIZE_ERR       =>   "حجم الملف كبير جداً!",

    Msg::NOT_VERIFIED      =>   "يرجى إدخال الرمز بشكل صحيح أدناه!",

    Msg::COMMENTED         =>   "تم استقبال تعليقكم وشكرا لتواصلكم!"
    
];