<?php

// DIRECTION CONSTANTS ======================

const DIR = "ltr";

const IS_RTL = false;

const TEXT_START = "left";

const TEXT_END = "right";

const TEXT_START_UC = "Left";

const TEXT_END_UC = "Right";

// ===============================================

const EDIT = "Bearbeiten";

const DELETE = "Gelöscht";

const SAVE = "Gespeichert";

const SEND = "Gesendet";

const VIEW = "Ansicht";

const YES = "Ja";

const NO = "Nein";


