<?php
return [

    'retype' => 'Retype',

    'delete_question' => 'Sind Sie sicher, dass Sie dieses Element löschen möchten: %s ?',

    'click_here_to_pick_up_date' => 'Klicken Sie hier, um das Datum abzuholen',

    'user_name' => "Benutzername",

    'password' => "Passwort",

    'sign_in' => 'Anmelden',

    'Verification' => 'Bitte Bestätigungscode eingeben',

    'login_failed' => 'Anmeldung fehlgeschlagen!',

    'tools' => 'Werkzeuge'

];