<?php
use Semiorbit\Data\Msg;

return [

    Msg::DBERR => "Entschuldigung! Ein unerwarteter Fehler ist aufgetreten. Bitte versuchen Sie es später noch einmal!",

    Msg::DBOK => "Erfolgreich gespeichert!",

    Msg::FILL_ALL => "Bitte alle Felder ausfüllen!",

    Msg::FILL_ALL_REQUIRED => "Bitte alle Pflichtfelder (*) ausfüllen!",

    Msg::DATA_EXISTS => "Daten existieren!",

    Msg::INVALID_TEL => "Bitte geben Sie eine gültige <em>Telefonnummer</em> ein! Es sind nur Ziffern erlaubt.",

    Msg::INVALID_VALUE => "Bitte geben Sie einen gültigen <em>Wert</em> ein!",

    Msg::INVALID_URL => "Bitte geben Sie eine gültige <em>Mobilnummer</em> ein! Es sind nur Ziffern erlaubt.",

    Msg::INVALID_EMAIL => "Bitte geben Sie eine gültige <em>E-Mail</em> ein!",

    Msg::RETYPE_PASSWORD => "Bitte <em>Passwort</em> erneut eingeben!",

    Msg::ROW_DELETED => "Erfolgreich entfernt!",

    Msg::REGISTER_OK => "Willkommen! Erfolgreich registriert.",

    Msg::REGISTER_CANCEL => "Registrierung abgebrochen!",

    Msg::REGISTER_ACTIVE => "Ihre Registrierung wurde reaktiviert. Danke!",

    Msg::REGISTER_FAILED => "Sie sind leider nicht registriert!",

    Msg::UPLOAD_OK => "Erfolgreich hochgeladen",

    Msg::UPLOAD_FAILED => "Hochladen fehlgeschlagen!",

    Msg::FILE_TYPE_ERR => "Ungültiger Dateityp!",

    Msg::RESIZE_FAILED => "Die Größe des hochgeladenen Fotos kann nicht geändert werden!",

    Msg::FILE_SIZE_ERR => "Ungültige Dateigröße!",

    Msg::NOT_VERIFIED => "Entschuldigung! Bitte geben Sie unten den korrekten Bestätigungscode ein.",

    Msg::COMMENTED => "Danke! Ihre Nachricht wurde erfolgreich versendet."

];