<?php
/** @var Semiorbit\Field\TextArea $field */

use Semiorbit\Auth\Auth;

$myTemplate = $field->ActiveTemplate();

?>
<div class="semiorbit-form-editor">

<?= $myTemplate->OpenField( $field ) ?>

	<?= $myTemplate->OpenLabel( $field ) . htmlspecialchars( $field->LabelText() ) . $field->RequiredMark() . $myTemplate->CloseLabel( $field )?>

	<?= $myTemplate->OpenInput( $field ) ?>

		<textarea  class="<?= $field->InputDefaultCssClass() ?>" cols="40" rows="8"  <?= $field->InputAttrs() ?>

                   title="<?=  htmlspecialchars( $field->LabelText() ) ?>" ><?=  htmlspecialchars( $field->Value )  ?></textarea>
<?php
if (!isset($GLOBALS['CKEDITOR_LOADED'])) :

    $GLOBALS['CKEDITOR_LOADED'] = true;

?>
<script src="<?=EXT?>ckeditor5/super-ckeditor.js"></script>
<script src="<?=EXT?>ckeditor5/translations/ar.js"></script>
<script src="<?=EXT?>ckeditor5/config.js"></script>
<script type="text/javascript">

    const ckConfig = CKEDITOR.customConfig;

    ckConfig.language = '<?= LANG ?>';

</script>
<?php endif ?>
<!--suppress JSUnresolvedVariable -->

<script type="text/javascript">

    CKEDITOR.ClassicEditor
        .create( document.getElementById( '<?=$field->DomInputID()?>' ), ckConfig)
        .catch( error => {
            console.error( error );
        } );

</script>

	<?= $myTemplate->CloseInput( $field ) ?>

	<?= $myTemplate->OpenNote( $field ) . ( $field->Note ) . $myTemplate->CloseNote( $field ) ?>

<?= $myTemplate->CloseField( $field ) ?>

</div>
