<?php
/**@var Semiorbit\Field\File $field **/

$myTemplate = $field->ActiveTemplate();

?>

<?= $myTemplate->OpenField( $field ) ?>

    <?= $field->Preview() ?>

	<?= $myTemplate->OpenLabel( $field ) . htmlspecialchars( $field->LabelText() ) . $field->RequiredMark() . $myTemplate->CloseLabel( $field )?>

	<?= $myTemplate->OpenInput( $field ) ?>

        <input type="file"  class="<?= $field->InputDefaultCssClass() ?>" value="<?= htmlspecialchars( $field->Value ) ?>" <?= $field->InputAttrs() ?>   title="<?=  htmlspecialchars( $field->LabelText() ) ?>" />

	<?= $myTemplate->CloseInput( $field ) ?>

	<?= $myTemplate->OpenNote( $field ) . ( $field->Note ) . $myTemplate->CloseNote( $field ) ?>

<?= $myTemplate->CloseField( $field ) ?>