<?php
/**@var Semiorbit\Field\Password $field **/

use Semiorbit\Field\Field;
use Semiorbit\Form\Form;

$myTemplate = $field->ActiveTemplate();

?>

<?= $myTemplate->OpenField( $field ) ?>

	<?= $myTemplate->OpenLabel( $field ) . htmlspecialchars( $field->LabelText() ?? '') . $field->RequiredMark() . $myTemplate->CloseLabel( $field )?>

	<?= $myTemplate->OpenInput( $field ) ?>

		<input type="password"  class="<?= $field->InputDefaultCssClass() ?>" value="<?= htmlspecialchars( $field->Value ?? '') ?>" <?= $field->InputAttrs() ?> title="<?=  htmlspecialchars( $field->LabelText() ) ?>"  />

	<?= $myTemplate->CloseInput( $field ) ?>

	<?= $myTemplate->OpenNote( $field ) . ( $field->Note ) . $myTemplate->CloseNote( $field ) ?>
	
	<?php if ( $field->Retype ) :

        $retype_value = ( Semiorbit\Auth\Auth::Check( $field->FillRetype ) ) ? $field->RetypeInputValue() : ''; ?>

	<?= $myTemplate->OpenLabel( $field ) . htmlspecialchars( $field->RetypeCaption ?? '') . $field->RequiredMark() . $myTemplate->CloseLabel( $field )?>

	<?= $myTemplate->OpenInput( $field ) ?>
	
			<input type="password"  id="retype-<?=  $field->DomInputID() ?>" class="<?= $field->InputDefaultCssClass() ?>" name="<?= $field->RetypeInputName() ?>" value="<?= htmlspecialchars( $retype_value ?? '') ?>" <?= $field->InputAttrs( [], array(Field::NAME) ) ?> title="<?=  htmlspecialchars( $field->RetypeCaption ) ?>"  />
	
	<?= $myTemplate->CloseInput( $field ) ?>
	
	
	<?php endif; ?>

<?= $myTemplate->CloseField( $field ) ?>

