<?php
/**@var Semiorbit\Field\Checkbox $field **/

$myTemplate = $field->ActiveTemplate();

$checked_html = (bool) $field->Value == true?  'checked value="1"' : 'value="0"';

?>


<?= $myTemplate->OpenField( $field ) ?>

	<?= $myTemplate->OpenLabel( $field ) . $myTemplate->CloseLabel( $field )?>

	<?= $myTemplate->OpenInput( $field ) ?>
	<div class="form-group">
		<div class="checkbox">
			<label>
				<input type="checkbox" <?= $field->InputAttrs() ?>   title="<?=  htmlspecialchars( $field->LabelText() ?? '') ?>"
                       <?=$checked_html?> onclick="if(this.checked){this.value='1';}else{this.value='0';}" >
				&nbsp; <?= htmlspecialchars( $field->LabelText() ?? '') ?>
			</label>
		</div>
	</div>
	<?= $myTemplate->CloseInput( $field ) ?>

	<?= $myTemplate->OpenNote( $field ) . ( $field->Note ) . $myTemplate->CloseNote( $field ) ?>

<?= $myTemplate->CloseField( $field ) ?>
