<?php
/**@var Semiorbit\Field\DateTime $field * */

use Semiorbit\Field\DateTime;
use Semiorbit\Translation\Lang;

$myTemplate = $field->ActiveTemplate();

if (!DateTime::CalendarLoaded()) :


endif;

DateTime::MarkCalendarLoaded();

$dom_id = $field->DomInputID();

?>

<?= $myTemplate->OpenField($field) ?>

<?= $myTemplate->OpenLabel($field) . htmlspecialchars($field->LabelText()) . $field->RequiredMark() . $myTemplate->CloseLabel($field) ?>

    <div class="input-group date">

        <input type="text" autocomplete="off" class="<?= $field->InputDefaultCssClass() ?>"
               value="<?= htmlspecialchars($field->Value) ?>" <?= $field->InputAttrs() ?>
               title="<?= htmlspecialchars($field->LabelText()) ?>"/>

        <span class="input-group-addon">

            <img id="img_<?= $dom_id ?>" name="img_<?= $field->Name ?>" style="cursor:pointer;"
                 src="<?= THEME ?>images/cal.gif" alt="<?= Lang::Trans("semiorbit::form.click_here_to_pick_up_date") ?>" />

        </span>

    </div>

<?= $myTemplate->OpenNote($field) . ($field->Note) . $myTemplate->CloseNote($field) ?>

<?= $myTemplate->CloseField($field) ?>