<?php if ( $this->Open ) : ?>

<?php if ($this->box_id == false) {$box_id = "group_0";} ?>

<div class="panel panel-primary  <?=( isset( $group['css_class'] ) ) ? $group['css_class'] : ''?>"  id="<?=$this->ID?>">


<div class="panel-heading">

    <?php if ($this->Title) : ?><span class="panel-title"><?=$this->Title?></span><?php endif; ?>

</div>


<div class="panel-body row">

    <?php if ( isset( $group['note'] ) ) : ?>

        <div class="semiorbit-form-group-note"><?=$group['note']?></div>

    <?php endif; ?>

<?php endif;

if ( $this->Close ) : ?>

</div>
</div>

<?php endif;