<?php
use Semiorbit\Output\Render;

Render::OpenBox(sign_in, array('signin', 'panel'));
?>
<!--START Menu Spot Area-->
<table align="center" style="padding:10px;padding-top:20px;padding-left:20px;margin:20px auto;">
<tr>
	<td>
	<?php if ($msg != '') : ?>
			<div class="signin_msg"><?=$msg?></div>
	<?php endif; ?>
	</td>
</tr>
<tr>
	<td>
		<form id="loginfrm" action="<?=BASE_URL?><?=LANG?>/signin/reg" method="POST" style="margin:0px; padding:0px;" target="_parent">
		<div class="field_label_n"><?=user_name?></div>
		<div class="txtfld_n"><input id="txtusr" name="txtusr" type="text" /></div>
		<div class="field_label_n"><?=password?></div>
		<div class="txtfld_n"><input id="txtpass" name="txtpass" type="password"  /></div>
		<div style="text-align:center; margin:10px; margin-left:10px;margin-bottom:0px;clear:both;"><input id="doit" style="cursor:pointer;" type="submit" value="<?=sign_in?>" /></div>
		</form>
	</td>
</tr>
</table>
<!--END Menu Spot Area-->

<?php 
Render::CloseBox(array('signin', 'panel'));