<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title><?=$TITLE?></title>

<?=$HEAD?>

<link href="../common/main_<?=$GLOBALS['lang']?>.css" rel="stylesheet" type="text/css" media="screen" />
<link rel="shortcut icon" type="image/x-icon" href="../favicon.ico" />

<script type="text/javascript" src="../cms/jquery-1.5.1.min.js"></script>
<script type="text/javascript" src="../cms/datagrid.js"></script>
<script type="text/javascript" src="../cms/jquery.fancybox-1.3.1.pack.js"></script>
<script type="text/javascript" src="../cms/jsysSlider.js"></script>
<script type="text/javascript" src="../common/js.php?lang=<?=$GLOBALS['lang']?>"></script>

</head>

<body>
<?=$CONTENT?>
</body>

</html>