<html lang="<?= LANG ?>">

<?php

use Semiorbit\Output\View;

/**@var $this View */
?>
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />

<title><?=$this->PageTitle() ?></title>


<link href="<?= THEME ?>css/style.css" rel="stylesheet" type="text/css" media="screen" />
<link rel="shortcut icon" type="image/x-icon" href="<?= PUBLIC_URL ?>favicon.ico" />


<script type="text/javascript" src="<?= THEME ?>js/script.js"></script>

</head>

<body>
<?= $this->Content() ?>
</body>

</html>