<?php
return array(

    ## -----------------------------------------------------------
	## AUTHENTICATION & USERS TABLE AND FIELDS
	## -----------------------------------------------------------
/*
	static $UsersModel = "Users";

	static $UsersModelFields = array('Identity'=>'Email', 'Password' => 'Password', 'Role' => 'UserRole');

	static $LoginIdentityInput = 'user_name';

	static $LoginPasswordInput = 'user_password';

	static $PasswordHash = 'md5';

    static $SuperAdminRoleId = 'A';
*/
);