<?php

use Semiorbit\Config\Config;

return [

    /*
    | -----------------------------------------------------------
    | DEFAULT PAGINATION WIDGET
    | -----------------------------------------------------------
    */

	Config::SCAFFOLDING__PAGINATION_WIDGET => "pagination",

    Config::SCAFFOLDING__PAGE_PARAM => "page",

	Config::SCAFFOLDING__ROWS_PER_PAGE => 6,


    /*
    | -----------------------------------------------------------
    | ERRORS
    | -----------------------------------------------------------
    */

    Config::SCAFFOLDING__SHOW_ERR_REPORT => false


];