<?php
return [

    'retype' => 'Dib u qor',

    'delete_question' => 'Ma hubtaa inaad doonayso inaad tirtirto shaygan: %s ?',

    'click_here_to_pick_up_date' => 'halkan ku dhufo si aad u soo qaadato taariikhda',

    'user_name' => "Magaca isticmaalaha",

    'password' => "Password",

    'sign_in' => 'See gal',

    'Verification' => 'Fadlan geli koodka xaqiijinta',

    'login_failed' => 'So galitaanku wuu fashilmay!',

    'tools' => 'Aalado'

];