<?php
use Semiorbit\Data\Msg;

return [

    Msg::DBERR => "Waan ka xunahay! Khalad lama filaan ah ayaa dhacay. Fadlan isku day mar kale hadhow!",

    Msg::DBOK => "Si guul leh ayaa loo badbaadiyey!",

    Msg::FILL_ALL => "Fadlan buuxi dhammaan goobaha!",

    Msg::FILL_ALL_REQUIRED => "Fadlan buuxi dhammaan goobaha loo baahan yahay (*)!",

    Msg::DATA_EXISTS => "Xogta ayaa jirta!",

    Msg::INVALID_TEL => "Fadlan geli <em>taleefoon</em>lambar sax ah! Kaliya lambarro ayaa la oggol yahay.",

    Msg::INVALID_VALUE => "Fadlan geli <em>qiimo</em> sax ah!",

    Msg::INVALID_URL => "Fadlan geli nambar <em>mobile</em> ansax ah! Tirooyinka kaliya ayaa la oggol yahay.",

    Msg::INVALID_EMAIL => "Fadlan geli <em>email</em> sax ah!",

    Msg::RETYPE_PASSWORD => "Fadlan ku celi <em>Password</em>!",

    Msg::ROW_DELETED => "Si guul leh ayaa meesha looga saaray!",

    Msg::REGISTER_OK => "Soo dhawoow! Si guul leh ayaa la isu diwaangeliyey.",

    Msg::REGISTER_CANCEL => "Diiwaangelintii waa la joojiyay!",

    Msg::REGISTER_ACTIVE => "Diiwaangelintaadii dib baa loo hawlgeliyay. Mahadsanid!",

    Msg::REGISTER_FAILED => "Waan ka xunahay ma aadan diwaan gashaneyn!",

    Msg::UPLOAD_OK => "Si guul ah loo soo geliyey",

    Msg::UPLOAD_FAILED => "Soodhigistii waa fashilantay!",

    Msg::FILE_TYPE_ERR => "Nooca faylka aan sax ahayn!",

    Msg::RESIZE_FAILED => "Ma bedeli karo sawirka la shubay!",

    Msg::FILE_SIZE_ERR => "Xajmiga faylka aan sax ahayn!",

    Msg::NOT_VERIFIED => "Waan ka xunahay! Fadlan hoos geli koodka xaqiijinta ee saxda ah.",

    Msg::COMMENTED => "Mahadsanid! Fariintaada si guul leh ayaa loo soo diray."

];