<?php

// DIRECTION CONSTANTS ======================

const DIR = "ltr";

const IS_RTL = false;

const TEXT_START = "left";

const TEXT_END = "right";

const TEXT_START_UC = "Left";

const TEXT_END_UC = "Right";

// ===============================================

const EDIT = "Wax ka bedel";

const DELETE = "la tirtiray";

const SAVE = "la badbaadiyey";

const SEND = "Diri";

const VIEW = "fiiri";

const YES = "Haa";

const NO = "Maya";


