<?php
return array(

    'retype' => 'Tekrar ',

    'delete_question' => 'Öğeyi silmek istediğnizden emin misiniz: %s ?',

    'click_here_to_pick_up_date' => 'Tarihi Seçmek İçin Buraya Tıklayın',

    'user_name' => "Kullanıcı Adı",

    'password' => "Şifre",

    'sign_in' => 'Giriş',

    'Verification' => 'Lütfen Kriterleri Uygun Yerine Giriniz',

    'login_failed' => 'Hatalı Giriş Bilgileri!',

    'tools' => 'Araçlar'

);