<?php
use Semiorbit\Data\Msg;

return [

    Msg::DBERR             =>   "Üzgünüz Yazarken Veritabanda Bir Hata Oluştu! Lütfen Daha Sonra Tekrar Deneyın...",

    Msg::DBOK              =>   "Veriler Başarıyla Kaydedildi!",

    Msg::FILL_ALL          =>   "Tüm Alanları Doldurmalısınız!",

    Msg::FILL_ALL_REQUIRED =>   "İstenen Tüm Alanları Doldurmalısınız (*) !",

    Msg::DATA_EXISTS       =>   "Veriler Mevcut..Lütfen Yeni Veriler Giriniz!",

    Msg::INVALID_TEL       =>   "Lütfen Numara Giriniz <em>Telefon</em> Doğru! Sadece Rakamlara izin Verilir..",

    Msg::INVALID_VALUE     =>   "Lütfen Giriniz <em>Miktar</em> Doğru!",

    Msg::INVALID_URL       =>   "Lütfe Numara Giriniz <em>Cep telefonu</em> Doğru!Sadece Rakamlara İzin Verilir.",

    Msg::INVALID_EMAIL     =>   "Lütfen Giriniz <em>E-posta</em> Doğru!",

    Msg::RETYPE_PASSWORD   =>   "Lütfen Tekrar Giriniz  <em>Şifre</em>!",

    Msg::ROW_DELETED       =>   "Başarıyla Silindi!",

    Msg::REGISTER_OK       =>   "Teşekürler!üyeliniz Başarıyla Oluştu...",

    Msg::REGISTER_CANCEL   =>   "Üyeliniz Başarıyla İptal Edildi! Teşekürler.",

    Msg::REGISTER_ACTIVE   =>   "Teşekürler! Üyeliniz Başarıyla Tekrar Oluştu ..",

    Msg::REGISTER_FAILED   =>   "Pardon! Önceden Bizde Kayıtlı Değilsiniz .",

    Msg::UPLOAD_OK         =>   "Dosyanız Başarıyla Yüklendi!",

    Msg::UPLOAD_FAILED     =>   "Yükleme sırasında Bir Hata Oluştu!",

    Msg::FILE_TYPE_ERR     =>   "Geçersiz Dosya Türü!",

    Msg::RESIZE_FAILED     =>   "Görüntü Boyutunu Değişimi Başarsız!",

    Msg::FILE_SIZE_ERR       =>   "Dosya Boyutu Çok Büyük!",

    Msg::NOT_VERIFIED      =>   "Lütfen Kodunuzu Doğru Bir Şekilde Aşağa Yazınız!",

    Msg::COMMENTED         =>   "Yorumlarınız Alındı Teşekkürler!"

];