<?php

// DIRECTION CONSTANTS ======================
const DIR = "ltr";
const IS_RTL = false;
const TEXT_START = "left";
const TEXT_END = "right";
const TEXT_START_UC = "Left";
const TEXT_END_UC = "Right";


define("Back", "Geri");
define("user_name", "Kullanıcı Adı");
define("password", "Şifre");
define("Re-Type", "Tekrar ");
define("sign_in", "Giriş");
define("sign_out", "Çıkış");
define("log_in", "Giriş");
define("Edit", "Düzenle");
define("AddNew", "Yeni Ekleme");
define("Delete", "Sil");
define("nowandate", date("Y-m-d H:i:s"));
define("date", date("Y-m-d"));
define("today", date("Y-m-d"));
define("delete_question", "Öğeyi silmek istediğnizden emin misiniz: %s ؟");
define("Save", "Kaydet");
define("Send","Gönder");
define("Login_Failed","Hatalı Giriş Bilgileri!");
define("more", "Daha Fazla");
define("NID", "ID");
define("Hidden","Gizle ( Ziyaretçiler Bu Kaydı Göremez");
define("LastUpdate","Son Güncelleme");
define("CreationDate", "Oluşturulma Tarihi");
define("NDate","Son Güncelleme");
define("Visits", "Ziyaretçiler");
define("lang","Dil");
define("Related_Pages","İlgili Sayfalar");
define("Visitors","Visits");
define("View","Görüntüle");
define("View_Orig_Page","Orjinal Sayfayı Görüntüle");
define("Home","Ana Sayfa");
define("Articles","Makaleler");
define("Read_More","Daha Fazla");
define("Remove_Pic","Resmi Sil");

define("aLinks","Kaynaklar ve Bağlantılar");
define("aPhotos","Görseller");
define("admin_controls","Denetim Masası");
define("enter_key_word","Aranacak Kelimeyi Girin");
define("Tools","Araçlar");
define("Cancel_Map_Point","İptal  Noktası");
define("ALL", "Hepsi");
define("Yes","Evet");
define("No","Hayır");
define("Start_Typing_Keywords", "Uygun Öğeyı Seç...");
define("ClickHereToPickUpDate", "Tarihi Seçmek İçin Buraya Tıklayın");
define("Male", "Bay");
define("Female", "Bayan");


define("You_can_contact_us_directly_by_filling_this_application", "Bizimle İrtibata Geçmek için Bu Formu Doldurunuz!");

define("v_delete_question", "Yorumu Silmek İstediğnizden Emin Misiniz: %s ?");
define("Hide","Gizle");
define("Show","Görüntüle");
define("Visitor_Name","Ad");
define("Del_Vcomments","Delete Comment");
define("Add_Vcomments","Buraya Yorumunuzu Yazabilirsiniz!");

define("yes","Evet");
define("no","Hayır");
define("read_more","Daha Fazla");
define("Verification","Lütfen Kriterleri Uygun Yerine Giriniz");
define("This_helps_us_to_prevent_automatic_registration","Aşağıda Gösterilen Karakterleri Giriniz (غير حساس لحالة الأحرف)");
define("Please_enter_the_string_shown_in_the_image_above","");
define("VComment_Text","Yorum Metni");
define("Set_Def_Pix","Görüntüleri Varsayılan Atama");
define("Search","Arama");
define("AdvSearch","Gelişmiş Arama +");
define("GuestBook","Ziyaretçi Defteri");
define("VComments","Ziyaretçi yorumlrı");

define("Required", "İstenilen");
define("Root", "--Kök-");
define("Public", "Kamu");
define("Private", "Özel");

define("MailList", "E-Posta Listesi");



/*
define("second","Saniye");
define("minute","Dakika");
define("hour","Saat");
define("day","Gün");
define("week","Hafta");
define("month","Ay");
define("year","Yıl");
define("decade","OnYıl");

define("seconds","Saniyeler");
define("minutes","Dakikalar");
define("hours","Saatler");
define("days","Günler");
define("weeks","Haftalar");
define("months","Aylar");
define("years","Yıllar");
define("decades","OnYıllar");

define("since","Beri");
define("ago","Önce");
define("m_ago","Geçe");
*/