<?php


// DIRECTION CONSTANTS ======================

const DIR = "ltr";

const IS_RTL = false;

const TEXT_START = "left";

const TEXT_END = "right";

const TEXT_START_UC = "Left";

const TEXT_END_UC = "Right";

// ===============================================

const EDIT = "Düzenle";

const DELETE = "Sil";

const SAVE = "Kaydet";

const SEND = "Gönder";

const VIEW = "Görüntüle";

const YES = "Evet";

const NO = "Hayır";