<?php if ($this->Open) : ?>

    <?php if ($box_id == false) {
        $box_id = "group_0";
    } ?>

    <fieldset  id="<?= $this->ID ?>">

    <legend>

        <?php if (stristr($this->Title, "ttxtg") == false) : ?>

            <span class="ttxtg"><?= $this->Title ?></span>

        <?php else : ?>

            <span><?= $this->Title ?></span>

        <?php endif; ?>

    </legend>

    <div class="field-set-wrap">

    <?php if (isset($grp['note'])) : ?>

        <div class="semiorbit-form-free-group-note"><?= $grp['note'] ?></div>

    <?php endif; ?>

<?php endif;

if ($this->Close) : ?>

    </div>
    </fieldset>

<?php endif;