<?php

// DIRECTION CONSTANTS ======================
const DIR = "ltr";
const IS_RTL = false;
const TEXT_START = "left";
const TEXT_END = "right";
const TEXT_START_UC = "Left";
const TEXT_END_UC = "Right";


define("Back","Back");
define("user_name","Username");
define("password","Password");
define("sign_out","Sign Out");
define("sign_in","Sign In");
define("log_in","Log In");
define("Edit","Edit");
define("Delete","Delete");
define("AddNew","Add New");
define("nowandate", date("Y-m-d H:i:s"));
define("date", date("Y-m-d"));
define("today", date("Y-m-d"));
define("ClickHereToPickUpDate", "Click here to pick up the date");
define("delete_question", "Are you sure want delete this item: %s ?");
define("Save", "Save");
define("more","Read More");
define("More","More");
define("NID","ID");
define("Hidden","Hidden");
define("LastUpdate","Last Update");
define("CreationDate", "Creation Date");
define("NDate","Last Update");
define("Visits","Visited");
define("lang","Language");
define("Related_Pages","Related Pages");
define("admin_controls","Admin Controls");
define("Related_Links","Related Links");
define("Visitors","Visits");
define("up","Up");
define("Home","Home");
define("Remove_Pic","Remove Image");
define("enter_key_word","Enter Keyword");
define("Login_Failed","Login Failed");
define("Re-Type","Re-Type ");
define("ALL", "All");
define("Tools","Tools");
define("Cancel_Map_Point","Cancel Map Point");
define("Male", "Male");
define("Female", "Female");

define("Send", "Send");


define("You_can_contact_us_directly_by_filling_this_application", "You can contact us directly by filling in this application!");
define("Start_Typing_Keywords", "Start typing here...");

define("v_delete_question", "Are you sure want to delete comment: %s ؟");
define("Hide","Hide");
define("Show","Show");
define("Visitor_Name","Visitor FullName");
define("Visitor_EMail","E-Mail");
define("View_Orig_Page","Source Page");
define("Del_Vcomments","Delete Comment");
define("Add_Vcomments","Leave A Comment!");

define("Yes","Yes");
define("No","No");
define("yes","yes");
define("no","no");
define("read_more","Read More");
define("Verification","Verification");
define("This_helps_us_to_prevent_automatic_registration","Please enter the displayed character below(case insensitive)");
define("Please_enter_the_string_shown_in_the_image_above","");
define("VComment_Text","Comment Text");

define("Search","Search");
define("AdvSearch","Advanced Search");
define("Change_Admin_Password", "Change Admin Password");

define("Required", "Required");
define("Root", "--Root--");
define("Public", "Public");
define("Private", "Private");


