<?php

// DIRECTION CONSTANTS ======================

const DIR = "ltr";

const IS_RTL = false;

const TEXT_START = "left";

const TEXT_END = "right";

const TEXT_START_UC = "Left";

const TEXT_END_UC = "Right";

// ===============================================

const EDIT = "Edit";

const DELETE = "Delete";

const SAVE =  "Save";

const SEND = "Send";

const VIEW = "View";

const YES = "Yes";

const NO = "No";


