<?php
return [

    'retype' => 'Retype ',

    'delete_question' => 'Are you sure you want delete this item: %s ?',

    'click_here_to_pick_up_date' => 'Click here to pick up the date',

    'user_name' => "Username",

    'password' => "Password",

    'sign_in' => 'Sign In',

    'Verification' => 'Please enter verification code',

    'login_failed' => 'Login failed!',

    'tools' => 'Tools'

];