<?php
use Semiorbit\Data\Msg;

return [

    Msg::DBERR             =>   "Sorry! An unexpected error occurred. Please try again later!",

    Msg::DBOK              =>   "Saved Successfully!",

    Msg::FILL_ALL          =>   "Please fill in all fields!",

    Msg::FILL_ALL_REQUIRED =>   "Please fill in all required fields (*)!",

    Msg::DATA_EXISTS       =>   "Data exists!",

    Msg::INVALID_TEL       =>   "Please enter a valid <em>phone</em> number! Only digits are allowed.",

    Msg::INVALID_VALUE     =>   "Please enter a valid <em>value</em>!",

    Msg::INVALID_URL    =>   "Please enter a valid <em>mobile</em> number! Only digits are allowed.",

    Msg::INVALID_EMAIL      =>   "Please enter a valid <em>email</em>!",

    Msg::RETYPE_PASSWORD   =>   "Please Retype <em>Password</em>!",

    Msg::ROW_DELETED       =>   "Removed Successfully!",

    Msg::REGISTER_OK       =>   "Welcome! Registered Successfully.",

    Msg::REGISTER_CANCEL   =>   "Registration Canceled!",

    Msg::REGISTER_ACTIVE   =>   "Your registration has been reactivated. Thanks!",

    Msg::REGISTER_FAILED   =>   "Sorry you are not registered!",

    Msg::UPLOAD_OK         =>   "Uploaded Successfully",

    Msg::UPLOAD_FAILED     =>   "Uploading Failed!",

    Msg::FILE_TYPE_ERR     =>   "Invalid File Type!",

    Msg::RESIZE_FAILED     =>   "Can not resize the uploaded photo!",

    Msg::FILE_SIZE_ERR     =>   "Invalid file size!",

    Msg::NOT_VERIFIED      =>   "Sorry! Please enter correct verification code below.",

    Msg::COMMENTED         =>   "Thank you! Your message was sent successfully."

];