<?php

// DIRECTION CONSTANTS ======================

const DIR = "ltr";

const IS_RTL = false;

const TEXT_START = "left";

const TEXT_END = "right";

const TEXT_START_UC = "Left";

const TEXT_END_UC = "Right";

// ===============================================

const EDIT = "Редактировать";

const DELETE = "Удалено";

const SAVE = "Сохранено";

const SEND = "Отправить";

const VIEW = "Просмотр";

const YES = "Да";

const NO = "Нет";


