<?php

use Semiorbit\Http\Url;

if ( $this->Open ) : ?>

    <?php $no_submit = ($this->read_only) ? 'onsubmit="return false"' : '' ?>

    <?php $read_only_class = ($this->read_only) ? ' form-read-only' : '' ?>

    <form method="<?=$this->method?>" action="<?=$this->action ?>" enctype="<?=$this->enctype?>" class="<?=$this->cssclass . $read_only_class?>" id="<?=$this->ID?>" <?=$no_submit?> >

    <?php if ($this->read_only) : ?><fieldset disabled><?php endif; ?>

<?php endif;

if ( $this->Close ) : ?>

    <?php if ($this->read_only) : ?></fieldset><?php endif; ?>

    </form>

<?php endif;