<?php
return [

    'retype' => 'Typ opnieuw ',

    'delete_question' => 'Weet je zeker dat je dit item wilt verwijderen: %s ?',

    'click_here_to_pick_up_date' => 'Klik hier om de datum te selecteren',

    'user_name' => "Gebruikersnaam",

    'password' => "Wachtwoord",

    'sign_in' => 'Aanmelden',

    'Verification' => 'Voer de verificatiecode in',

    'login_failed' => 'Aanmelden mislukt!',

    'tools' => 'Gereedschap'

];
