<?php
use Semiorbit\Data\Msg;

return [

    Msg::DBERR             =>   "Sorry! Er is een onverwachte fout opgetreden. Probeer het later opnieuw!",

    Msg::DBOK              =>   "Succesvol opgeslagen!",

    Msg::FILL_ALL          =>   "Vul alle velden in!",

    Msg::FILL_ALL_REQUIRED =>   "Vul alle verplichte velden (*) in!",

    Msg::DATA_EXISTS       =>   "Gegevens bestaan al!",

    Msg::INVALID_TEL       =>   "Voer alstublieft een geldig <em>telefoon</em>nummer in! Alleen cijfers zijn toegestaan.",

    Msg::INVALID_VALUE     =>   "Voer alstublieft een geldige <em>waarde</em> in!",

    Msg::INVALID_URL       =>   "Voer alstublieft een geldige <em>URL</em> in!",

    Msg::INVALID_EMAIL     =>   "Voer alstublieft een geldig <em>email</em>adres in!",

    Msg::RETYPE_PASSWORD   =>   "Voer alstublieft het <em>wachtwoord</em> opnieuw in!",

    Msg::ROW_DELETED       =>   "Succesvol verwijderd!",

    Msg::REGISTER_OK       =>   "Welkom! Succesvol geregistreerd.",

    Msg::REGISTER_CANCEL   =>   "Registratie geannuleerd!",

    Msg::REGISTER_ACTIVE   =>   "Uw registratie is opnieuw geactiveerd. Bedankt!",

    Msg::REGISTER_FAILED   =>   "Sorry, u bent niet geregistreerd!",

    Msg::UPLOAD_OK         =>   "Succesvol geüpload!",

    Msg::UPLOAD_FAILED     =>   "Uploaden mislukt!",

    Msg::FILE_TYPE_ERR     =>   "Ongeldig bestandstype!",

    Msg::RESIZE_FAILED     =>   "Kan de geüploade foto niet verkleinen!",

    Msg::FILE_SIZE_ERR     =>   "Ongeldige bestandsgrootte!",

    Msg::NOT_VERIFIED      =>   "Sorry! Voer hieronder de juiste verificatiecode in.",

    Msg::COMMENTED         =>   "Bedankt! Uw bericht is succesvol verzonden."

];
