<?php

// DIRECTION CONSTANTS ======================

const DIR = "ltr";

const IS_RTL = false;

const TEXT_START = "left";

const TEXT_END = "right";

const TEXT_START_UC = "Left";

const TEXT_END_UC = "Right";

// ===============================================

const EDIT = "Bewerken";

const DELETE = "Verwijderen";

const SAVE = "Opslaan";

const SEND = "Verzenden";

const VIEW = "Bekijken";

const YES = "Ja";

const NO = "Nee";


